// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpddakfcjkmhqindhmjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZGRha2ZjamttaHFpbmRobWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDY2MDEsImV4cCI6MjA2Nzg4MjYwMX0.PQGvP1Z7xKMTAFMECHf5PEgSzxJXUa90UL34cm7qalo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});